# Generated by Django 3.2.3 on 2021-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210526_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='from_user',
            field=models.BooleanField(default=True),
        ),
    ]
